name: Metrics
on:
  # Schedule updates
  schedule: [{ cron: "0 22 * * 0" }]
  workflow_dispatch:
  push: { branches: "main" }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: commit
          committer_message: "chore: update metrics"
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: yes
          plugin_languages_recent_load: 600
          plugin_languages_recent_days: 30
          plugin_stars: yes
          debug: yes
